version: '3.8'

services:
  geth:
    image: ernest/eth
    restart: always
    container_name: 'geth'
    environment:
      BLOCK_SIGNER_KEY: 'dae1a9bffa1a808d3e957fdec61e0979e412206bde948d0e29d925acada9ad82'
      BLOCK_SIGNER_ADDRESS: '0xbb8227fc9e5716d12f4b4eea18ac2b188cf19851'
    ports:
      - 8545:8545
    networks:
      localnet:
        ipv4_address: 192.167.0.2

  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    networks:
      localnet:
        ipv4_address: 192.167.0.3

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:4.1.7
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: 'http://192.167.0.2:8545/'
      DATABASE_URL: 'postgresql://postgres:@192.167.0.3:5432/blockscout?ssl=false'
      ETHEREUM_JSONRPC_TRACE_URL: 'http://192.167.0.2:8545/'
      ECTO_USE_SSL: 'false'
      PORT: '4000'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
    ports:
      - 4000:4000
    networks:
      localnet:
        ipv4_address: 192.167.0.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.0.0/16